In [1]:
###  tranzendo novas analises

In [24]:
import pandas as pd

# Carrega todas as linhas do arquivo como texto
with open('Relatorio_Atendimento_dos_Profissionais_janeiro.csv', 'r', encoding='latin1') as f:
    linhas = f.readlines()

blocos = []
nome = ''
cargo = ''
quantidade1 = ''
quantidade2 = ''
tempo_total = ''

for linha in linhas:
    linha = linha.strip()

    # Detectar linhas com nome + cargo + quantidade
    if ';' in linha and linha.count(';') >= 5 and not linha.split(';')[0].isdigit():
        partes = linha.split(';')
        nome = partes[0].strip()
        cargo = partes[1].strip()
        quantidade1 = partes[2].strip()
        quantidade2 = partes[3].strip()
        tempo_total = partes[4].strip()

        # Armazena esse registro de quantidade
        blocos.append({
            'Nome': nome,
            'Cargo': cargo,
            'Quantidade1': quantidade1,
            'Quantidade2': quantidade2,
            'Tempo': tempo_total,
            'Setor': '',
            'Tipo_Atendimento': '',
            'Data_Entrada': '',
            'Data_Saida': '',
            'Duracao': ''
        })

    # Linha de atendimento (início com código)
    elif linha and linha[0].isdigit() and ';' in linha:
        partes = linha.split(';')
        bloco = {
            'Nome': nome,
            'Cargo': cargo,
            'Quantidade1': '',
            'Quantidade2': '',
            'Tempo': '',
            'Setor': partes[3].strip() if len(partes) > 3 else '',
            'Tipo_Atendimento': partes[4].strip() if len(partes) > 4 else '',
            'Data_Entrada': partes[6].strip() if len(partes) > 6 else '',
            'Data_Saida': partes[7].strip() if len(partes) > 7 else '',
            'Duracao': partes[8].strip() if len(partes) > 8 else ''
        }
        blocos.append(bloco)

# Criar DataFrame
df_tudo = pd.DataFrame(blocos)

# Salvar como CSV
df_tudo.to_csv('base_completa_com_quantidades_e_atendimentos.csv', sep=';', index=False, encoding='latin1')

In [25]:
df_tudo

,Nome,Cargo,Quantidade1,Quantidade2,Tempo,Setor,Tipo_Atendimento,Data_Entrada,Data_Saida,Duracao
0,Período,01/01/2025 00:00,31/01/2025 23:59,,,,,,,
1,,,,,,,,,,
2,Unidade Funcional,PRONTO SOCORRO,,,,,,,,
3,,,,,,,,,,
4,Total Geral de Atendimentos,Total Geral de FA,Tempo Total Geral,,,,,,,
...,...,...,...,...,...,...,...,...,...,...
55086,FA,Consulta,,,,PS CLÍNICA MÉDICA,CONSULTA_ASSISTENCIAL,23/01/2025 05:44,23/01/2025 05:50,06min:09s
55087,FA,Consulta,,,,PS CLÍNICA MÉDICA,CONSULTA_ASSISTENCIAL,23/01/2025 06:07,23/01/2025 06:15,08min:03s
55088,FA,Consulta,,,,PS CLÍNICA MÉDICA,CONSULTA_ASSISTENCIAL,23/01/2025 06:30,23/01/2025 06:35,04min:49s
55089,FA,Consulta,,,,PS CLÍNICA MÉDICA,CONSULTA_ASSISTENCIAL,23/01/2025 06:36,23/01/2025 06:40,04min:34s
55090,FA,Consulta,,,,PS CLÍNICA MÉDICA,CONSULTA_ASSISTENCIAL,23/01/2025 06:41,23/01/2025 06:51,09min:19s

In [26]:
# Carregue o arquivo original
df = pd.read_csv('base_completa_com_quantidades_e_atendimentos.csv', sep=';', encoding='latin1')

# Remover linhas completamente vazias
df_clean = df.dropna(how='all')

# Remover duplicatas
df_clean = df_clean.drop_duplicates()

# Salvar o CSV limpo
df_clean.to_csv('base_completa_limpa.csv', sep=';', index=False, encoding='latin1')

# Visualizar as primeiras linhas
df_clean.head(10)

,Nome,Cargo,Quantidade1,Quantidade2,Tempo,Setor,Tipo_Atendimento,Data_Entrada,Data_Saida,Duracao
0,Período,01/01/2025 00:00,31/01/2025 23:59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Unidade Funcional,PRONTO SOCORRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Total Geral de Atendimentos,Total Geral de FA,Tempo Total Geral,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Total Geral de Atendimentos,Total Geral de FA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Profissional,CBO,Total Atendimento,Total FA,Temp. Total Atend.,NaN,NaN,NaN,NaN,NaN
9,ABIGAIL FERREIRA PIRES,ENFERMEIRO,162,162,09h:43min:32s,NaN,NaN,NaN,NaN,NaN
10,FA,Consulta,Local de Atendimento,Especialidade,Tipo Atendimento,NaN,NaN,NaN,NaN,NaN
11,FA,Consulta,NaN,NaN,NaN,PS CLÍNICA MÉDICA,CLASSIFICACAO_RISCO,01/01/2025 12:03,01/01/2025 12:06,03min:43s
12,FA,Consulta,NaN,NaN,NaN,PS CLÍNICA MÉDICA,CLASSIFICACAO_RISCO,01/01/2025 12:18,01/01/2025 12:21,03min:28s
13,FA,Consulta,NaN,NaN,NaN,PS CLÍNICA MÉDICA,CLASSIFICACAO_RISCO,01/01/2025 12:44,01/01/2025 12:47,02min:59s